### ISSUE TITLE
Tycho and Crossflow

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#133]
Hello,

In the current version of Scava in the dev branch, the projects related to Crossflow are now available. However, they are not Maven projects yet. 

Currently, one of our readers, make use of a component found in Crossflow (the GitHub RESTMULE). While this works perfectly by cloning the repository, I have seen that Jenkins is not able to create a build version of my branch because the Maven install process is not finding the Crossflow components. I'm guessing because they are not maven and have not been defined in the parent POM file of metric-platform. 

Thus, I would like to know whether the projects from Crossflow are going to be included in the parent POM file of metric-platform or not? If not, which is the solution that I would need to follow to have a build of my branch (and in consequence of the merged branch).

**Comment by creat89** [comment]
What I am seeing is that Maven is looking externally the dependencies instead of looking for them internally.

**Comment by tdegueul** [comment]
Indeed, Crossflow is not part of our Tycho build yet. I tried to copy the Jenkinsfile that York was using for the external repository [here](https://github.com/crossminer/scava/blob/dev/crossflow/Jenkinsfile) but I couldn't make it work.

AFAIK, there is no `pom.xml` file in [the crossflow directory](https://github.com/crossminer/scava/blob/dev/crossflow/) yet.

@patrickneubauer @kb634 @kolovos  could you please look into it and try to come up with a set of `pom.xml` files that would build Crossflow automatically from source using Tycho?

Then I'll be able to create  a Jenkins file for Crossflow (similar to [this one](https://github.com/crossminer/scava/blob/dev/metric-platform/Jenkinsfile)) and build it on the CI, so that @creat89 can finally use it ;)

**Comment by creat89** [comment]
For the moment, in order to make available the newest reader of GitHub, I have converted the elements from Crossflow that we use into jars as recommended me @kb634. However, I know that this is not the best solution.

**Comment by kb634** [comment]
5f373d669df2930faab38c590499cb9f84c24571 introduces parent poms for crossflow and restmule (in their respective folders), integrated with Tycho, ready to be added to the CI.

**Comment by creat89** [comment]
Hello @tdegueul,

Could you create a Jenkinsfile for Restmule? As you can see I had issue #403, which at the end the problem was that Jenkins is not building yet Restmule.

**Comment by tdegueul** [comment]
I pushed a `Jenkinsfile` for Crossflow and Restmule in f0bc02962412783f962c0ece49a72df5ff789647 and 874aba32be3464d6ea9e2367ae04fe80eb3f303d. The corresponding CI jobs are [scava-crossflow](http://ci5.castalia.camp:8080/job/scava-crossflow/) and [scava-restmule](http://ci5.castalia.camp:8080/job/scava-restmule/).

I archive all JARs in any `target/` folder for both jobs. See [Crossflow's artifacts](http://ci5.castalia.camp:8080/job/scava-crossflow/job/dev/lastSuccessfulBuild/artifact/crossflow/) and [Restmule's artifacts](http://ci5.castalia.camp:8080/job/scava-restmule/job/dev/lastSuccessfulBuild/artifact/restmule/). @kb634 please check if this is fine for you.

@creat89 I believe this won't be sufficient to solve your issue; we'll probably have to include (part of) Restmule in the `metric-platform/` build. Let's talk later.
