### ISSUE TITLE
SCAVA metrics moslty empty

### ISSUE THREAD

**Issue by valeriocos** [crossminer/scava#139]
I'm using the [docker-compose](https://github.com/crossminer/scava-deployment/blob/dev/docker-compose-build.yml) available in the scava-deployment repo. I'm querying the SCAVA API to collect the metrics of the projects available in the docker-compose.

I see that most metrics returned from the SCAVA API are empty (their datatable is empty), see examples below.

I'm using the following endpoints to query the API (I have tried the ones available at https://github.com/crossminer/scava/wiki/REST-API-Documentation#metrics-provider-api, but they don't seem to work)
- `/metrics/`
- `/factoids/`
- `/projects/`
- `/projects/p/<project-id>/m/<metric-id>`
- `/projects/p/<project-id>/f/<factoid-id>`

I don't know if this problem is related to the endpoints I'm using, comes from the metricprovider. or just that most metrics have zero values. Any help @ambpro @md2manoppello ?

**emf**
Total metrics collected: 188 (183 empty, empty datatable) 
306 listed in http://localhost:5601/project/configure/emf

**JDBM**
Total metrics: 188, 183 empty
306 listed in http://localhost:5601/project/configure/JDBM

**gef**
Total metrics: 188, 101 empty
306 listed in http://localhost:5601/project/configure/gef

**SVNKIT**
Total metrics: 188, 138 empty
306 listed in http://localhost:5601/project/configure/SVNKIT

**netty**
Total metrics: 188, 138 empty
306 listed in http://localhost:5601/project/configure/netty

**Activemq**
Total metrics: 188, 188 empty
306 listed in http://localhost:5601/project/configure/Activemq

**elasticsearchjavaclient**
Total metrics: 188, 117 empty
306 listed in http://localhost:5601/project/configure/elasticsearchjavaclient

**elasticsearchjavaclient**
Total metrics: 188, 117 empty
306 listed in http://localhost:5601/project/configure/elasticsearchjavaclient

**Comment by borisbaldassari** [comment]
Same here, with roughly the same amount of empty values..

**Comment by davidediruscio** [comment]
@ambpro Could you please check if you have the same situation on your local installation?

**Comment by creat89** [comment]
I'm working with @mhow2, on their server (I guess docker image too) and we're having a similar issue. In our case, some metrics despite being executed according to the log, they do not create a a collection or the collection is completely empty. At the beginning I thought that it was due to a metric dependency that was missing, but after some executions, in which the dependency was called and executed, still many other metrics collections are empty.

One of our reasons, might be that the metric plain text is not creating a collection, despite being executed, and in consequence is affecting the output of others. I haven't seen this effect on a local version using the code from GitHub.
