### ISSUE TITLE
Register Project: Mantis BT, BitBucket

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#175]
Hello,

In Scava UI there are missing two bug tracker systems: Mantis BT and BitBucket. Could you add them to the UI, so the user partners can start checking that the readers work correctly?

**Comment by ambpro** [comment]
Hello @creat89 , could you please test it on your side ?

**Comment by creat89** [comment]
Hello @ambpro, I've just tested the BitBucket reader and it is returning me the following error:
```
oss-app_1         | Caused by: java.lang.NullPointerException
oss-app_1         |     at org.eclipse.scava.platform.client.api.ProjectCreationResource.createProject(ProjectCreationResource.java:172)
oss-app_1         |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
oss-app_1         |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
oss-app_1         |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
oss-app_1         |     at java.lang.reflect.Method.invoke(Method.java:498)
oss-app_1         |     at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
oss-app_1         |     ... 47 more
```
As well, I'm seeing that the reader has multiple methods that are redundant. So, I'll ask Dan to remove some (user, repository and owner). In the mean time, could you just show url, login and password. We'll make that the reader uses the url to parse the information necessary regarding owner and repository.

**Comment by creat89** [comment]
Hello @ambpro, creating a project with Mantis BT seems to be generating the correct entry in the DB. Nonetheless, similar to BitBucket, could you remove from the interface and the project creation code the fields `project_id` and `host`? I'll modify the code of Mantis BT, so this information is obtained from the URL.

**Comment by ambpro** [comment]
@creat89 , https://github.com/crossminer/scava/commit/c273022c53d4ec3613eb6e546581a0fc6106f5eb should fix the bts redundant param.

**Comment by Danny2097** [comment]
@ambpro / @creat89 
In commit:https://github.com/crossminer/scava/commit/679abf60d2ea5db1dbca2be2a77b5ba034816c80 I made the following changes to the **Mantis** repository model;

- Removed `host`: this was redundant as `url` is sufficient.
- Refactored `project_id` to `project_identifier`.

Due to the nature of MantisBT we are unable to remove the `project_identifier` as this is required when requesting data using the REST API and cannot be obtained from the URL. Therefore `project_identifier` is a necessary parameter when analysing a project hosted in a MantisBT instance.

Note: minor refactoring of the reader was also required.

In commit d255203 I made the following changes to the **Bitbucket** repository model;
- Removed `host`, `repository` and `owner` parameters

**Comment by ambpro** [comment]
Hello @creat89, could we close the issue as the requirement is addressed ?

**Comment by creat89** [comment]
@ambpro I think @Danny2097 needs that for MantisBT a project identifier field.

**Comment by Danny2097** [comment]
> @ambpro I think @Danny2097 needs that for MantisBT a project identifier field.

Yes this is correct.
