### ISSUE TITLE
GitHub Reader: "Do not know how to handle this type of error code: 404"

### ISSUE THREAD

**Issue by MarcioMateus** [crossminer/scava#187]
We are getting the following error on during the execution of the metric platform:

```
18:36:29.680 ERROR [172] AbstractInterceptor$1 - UNKNOWN ERROR CODE: 404
Exception in thread "pool-193-thread-1" java.lang.UnsupportedOperationException: Do not know how to handle this type of error code: 404
	at org.eclipse.scava.crossflow.restmule.core.interceptor.AbstractInterceptor$1.intercept(AbstractInterceptor.java:173)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

I believe that the error is not related with the execution of any metric but with the Delta creation.

I also found the following lines before the error (not sure if related):
```
No authentification data has ben set, using public access
INFO : GitHub Session Created.
```

**Comment by tdegueul** [comment]
Seems related to Crossflow, not the platform? @crossminer/york

Just a wild guess: are you trying to clone a private GitHub repository? If so, do you have a GitHub token? Without the proper GitHub token, the server will throw a `404` at you. In the metric platform, you can configure it through the admin UI; I don't know if Crossflow picks it from here or another place though.

**Comment by creat89** [comment]
This is more related to GitHub reader which in fact uses CROSSFLOW/RESTMULE, than to CROSSFLOW/RESTMULEuniquely.  As @tdegueul says if you're trying to import a private GitHub repository it is necessary to include a GitHub token. If you're using the UI and importing the project from there, the importer will add automatically the token to the reader. If not, you'll need to add the bugtracker system with a password/user or token. 

GitHub reader can only use public access for analyzing public repositories. In the case that you're trying to read a public repository, let me know the name of it, and EHU will try to reproduce the error.

**Comment by MarcioMateus** [comment]
Yes, we created the property `githubToken` on the administration dashboard. Nevertheless, the project that we are trying to analyse is public.

[https://github.com/sparkfun/SparkFun_MPL3115A2_Breakout_Arduino_Library](url)

Thanks

**Comment by creat89** [comment]
@MarcioMateus, I don't know what to answer you, because I arrived to reproduce sometimes the error, but not always, either using a token or not. In most cases, everything run perfectly, so I don't know which is the exact error. And yes, the error is closer to CROSSFLOW/RESTMULE than to us. It might be the case that the RESTMULE do not like a JSON that returns no issues. Still, I have pushed a commit (https://github.com/crossminer/scava/commit/84b2f624e671cdea72e391dd94237d142adfd7b1) that should prevent some issues that are triggered when you import a GitHub project and you haven't declared a GitHub token. This might have been the reason. 

In all the cases, any token (GitLab or GitHub) is added to the reader at the import time. So, it is necessary that you import from scratch the project after you have added the Token. Otherwise, the reader will still be using the public session. 

Let me know if this solves the issue.

**Comment by MarcioMateus** [comment]
> So, it is necessary that you import from scratch the project after you have added the Token. Otherwise, the reader will still be using the public session.

That may be the problem. I think that we probably added the project before defining the token. We added some other projects after the token and didn't have this problem.

We will try it out.

**Comment by creat89** [comment]
We have found the reason for the issue. @Danny2097 or @creat89 will push the fix ASAP.

**Comment by creat89** [comment]
I have pushed a new commit solving the issue with GitHub reader. The error was from our side. Commit https://github.com/crossminer/scava/commit/0277f175a82a0b1bb267c2dec22362bccdb17ac2 should fix this problem.
