### ISSUE TITLE
Projects are not dropped from scava-analysis

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#206]
Hello,

This issue is similar to https://github.com/crossminer/scava/issues/179 but different in the sense that projects are not being dropped,  after being deleted in the platform, from the `scava-analysis` db, more specifically from the `projects`. 

This happens after at least one analysis task has been created for the project. If the task is deleted or the project is deleted, the entry in  `scava-analysis/projects` is still there. 

Can anyone reproduce this issue?

**Comment by ambpro** [comment]
@creat89 , I pushed a quick fix for this issue. 

> If the task is deleted or the project is deleted, the entry in scava-analysis/projects is still there.

The expected behavior is to remove the associated `project` document including its `analysisTasks` documents from the `scava-analysis` database  when a project is removed from the admin-ui.
However, when a task is removed the `project` document is not concerned.

**Comment by mhow2** [comment]
On my side (and as of today build), when I delete a project I observe what @ambpro explained above, which looks consistent.
