### ISSUE TITLE
prosoul : Can't find value for for XXX

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#265]
:exclamation: I notice the following error because of env `DASHDEBUG=1`
In the current prosoul build we have hundred of errors like follow at startup (and notice "for for") :

```
$ docker logs scava-deployment_prosoul_1 2>&1|grep 'value for'
2019-06-04 07:49:46,063 Can't find value for for AvgActiveUsers
2019-06-04 07:49:46,070 Can't find value for for AvgNewUsers
2019-06-04 07:49:46,081 Can't find value for for NumOfReplies
2019-06-04 07:49:46,088 Can't find value for for NumOfComments
2019-06-04 07:49:46,099 Can't find value for for numberOfBugs
2019-06-04 07:49:46,113 Can't find value for for numOfCommits
```

**Comment by valeriocos** [comment]
Thank you @mhow2 for reporting this issue. I did a docker system prune, deployed the last docker-compose and I'm not able to replicate the issue:
```
slimbook@slimbook-KATANA:~/Escritorio/sources/scava$ docker logs scava-deployment_prosoul_1 2>&1 | grep 'value for'
slimbook@slimbook-KATANA:~/Escritorio/sources/scava$ 
```

Is it possible you are not using the last prosoul image ?

**Comment by valeriocos** [comment]
As discussed offline, the message appears only when `DASHDEBUG` is set to 1 in the prosoul section of the scava-deployment's docker-compose.

The message is due to an empty value returned by the assessment: https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/prosoul_assess.py#L386

Probably the log message should be improved, for instance including the from and to dates

**Comment by valeriocos** [comment]
A PR is available on Prosoul: https://github.com/Bitergia/prosoul/pull/150
@mhow2 I'll merge it, so then we can check the log messages (which now includes the from and to date) with the metrics data.

**Comment by mhow2** [comment]
Thanks !
