### ISSUE TITLE
Project import doesn't manage correctly Eclipse projects with dashes (-) in their identifiers

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#343]
When using either the Admin UI or the API to create an Eclipse project, it seems that project EMF Parsley [1] cannot be imported. Nothing happens in the UI, and the API returns a 400 error code.

[1] https://projects.eclipse.org/projects/modeling.emf-parsley

**Comment by creat89** [comment]
Hello Boris,

Just by curiosity, I checked the code and I think the reason is because the first line of the importer method does a replacement in the URL: 

```
String JSON_URL_PROJECT = "https://projects.eclipse.org/json/project/" + projectId.replaceAll("-", "\\.");
```

Which will generate a completely different URL to the one expected, i.e. https://projects.eclipse.org/projects/modeling.emf\.parsley.

Have you tried to test another project from Eclipse without a dash in the URL?

In all the cases, I'm guessing that @md2manoppello should be able to help you as the code was developed by L'Aquila.

**Comment by borisbaldassari** [comment]
Hey @creat89, thanks for the feedback. This was my guess too (the dash in the project name), since I've imported a bunch of projects already and it happened only on this one. I'll try another dash-named project to make sure it is reproducible, but I'm quite confident it's somehow related to the dash.

**Comment by borisbaldassari** [comment]
I confirm that it happens also on `modeling.emft.emf-store`, giving some more credit to the dash story.

**Comment by creat89** [comment]
Well, if you have tested other projects that do not contain dashes, then the issue is that the dash is converted into  `\.`, in the first line  which makes the URL different.
