### ISSUE TITLE
Wrong task status for project 

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#344]
Netty is part of the projects automatically imported from the data dumps. It is displayed as "Analysis in progress" and the task is marked as EXECUTION but it isn't running actually, there is no task associated to the project in the workers or in the pending list.

![Capture du 2019-09-02 23-00-42](https://user-images.githubusercontent.com/5849071/64133394-132e2f00-cdd6-11e9-9a17-d669685291c6.png)
![Capture du 2019-09-02 23-03-46](https://user-images.githubusercontent.com/5849071/64133395-132e2f00-cdd6-11e9-84c4-092df0d4cc5c.png)

**Comment by ambpro** [comment]
Hi @borisbaldassari ,
I believe that this behavior is not an analysis issue on the metric-platform component.
What you 're looking above is the state of the project at the moment when I exported the project's dump.
FYI, the way in order to push a task on a free worker is that this task must be in `Pending_Execution` state (which is not the case for this task). Moreover, the project's data dumps is outdated and should be no longer in use.

**Comment by borisbaldassari** [comment]
Hi @ambpro,
I don't think it is an analysis issue, it's just not consistent. Low priority for sure.
What do you mean when you say it should not be used anymore? I updated the instance recently and the import is still present in the docker-compose file as far as I can tell.

**Comment by ambpro** [comment]
Hi @borisbaldassari,

> What do you mean when you say it should not be used anymore?

The data dumps on [M24](http://ci3.castalia.camp/dl/M24/) is outdated because of the analysis data models refactoring done a few weeks ago. It's recommanded to move to [M30](http://ci3.castalia.camp/dl/M30/).

>  I updated the instance recently and the import is still present in the docker-compose file as far as I can tell.

You should edit the oss-db [Dockerfile](https://github.com/crossminer/scava-deployment/blob/dev/oss-db/Dockerfile#L13) and update the appropriate data dumps links before rebuild the stack again!

**Comment by borisbaldassari** [comment]
Created [#98 in scava-deployment](https://github.com/crossminer/scava-deployment/issues/98) git repository and fixed the Dockerfile.
