### ISSUE TITLE
KB crashed with a memory issue

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#429]
I Cannot reach anymore the KB.
@blueoly told me this is a memory issue.
Could you have a look at it?
Thx a lo

FYI: http://83.212.75.210:8080/swagger-ui.html

**Comment by jdirocco** [comment]
Hi @phkrief ,
I restarted the KB services and it works. In my opinion, the crashes depend on the memory available on the server. I recognized that it happens every Sunday afternoon because the KB recomputes all distance matrices. It doesn't happen in other installations (my private installation relies on a server equipped with 16Gb of Ram). @blueoly,  could you check the memory settings? I can disable the scheduled task as the last option.

**Comment by phkrief** [comment]
Thanks a lot @md2manoppello .
WOuld it make sense to tell me how to restart the KB Services to avoid bothering you (every Sunday) ? ;-)
Thx again for your help
